{% set name = "stratocaster" %}
{% set version = "0.1.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OpenFreeEnergy/stratocaster/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b1e251878d27c29b7e9786497f403060e70cacc030ee42dac7889ee24c49ccaf
build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - versioningit
  run:
    - python >={{ python_min }}
    - gufe >=1.2.0,<1.3.0

test:
  imports:
    - stratocaster
  requires:
    - pytest
    - python {{ python_min }}
  commands:
    - pytest --pyargs stratocaster

about:
  home: https://github.com/OpenFreeEnergy/stratocaster
  summary: 'Edge computation prioritization strategies for gufe AlchemicalNetworks'
  description: |
    stratocaster defines and provides a framework for creating a
    ranking of Transformations within a gufe AlchemicalNetwork to
    optimize execution order.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/OpenFreeEnergy/stratocaster

extra:
  recipe-maintainers:
    - dotsdl
    - ianmkenney
    - mikemhenry
